USE ROLE ACCOUNTADMIN;

-- Create role for project
CREATE ROLE IF NOT EXISTS FINLAB_ROLE;
GRANT ROLE FINLAB_ROLE TO USER <tcsimm>;

-- Create a warehouse / compute power
CREATE WAREHOUSE IF NOT EXISTS FINLAB
    WAREHOUSE_SIZE = XSMALL
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

GRANT USAGE ON WAREHOUSE FINLAB_WH TO ROLE FINLAB_ROLE;

-- Create database and schemas
CREATE DATABASE IF NOT EXISTS FINLAB;
CREATE SCHEMA IF NOT EXISTS FINLAB.BRONZE;
CREATE SCHEMA IF NOT EXISTS FINLAB.SILVER;
CREATE SCHEMA IF NOT EXISTS FINLAB.GOLD;

-- Give project role control of the database & schemas
GRANT OWNERSHIP ON DATABASE FINLAB TO ROLE FINLAB_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA FINLAB.BRONZE TO ROLE FINLAB_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA FINLAB.SILVER TO ROLE FINLAB_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA FINLAB.GOLD   TO ROLE FINLAB_ROLE COPY CURRENT GRANTS;

-- Switch to project role and warehouse
USE ROLE FINLAB_ROLE;
USE WAREHOUSE FINLAB_WH;
USE DATABASE FINLAB;
USE SCHEMA BRONZE;

-- Create raw prices table for ingestion
CREATE OR REPLACE TABLE PRICES_RAW (
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    TICKER STRING,
    DATA VARIANT
);
