USE ROLE ACCOUNTADMIN;
SELECT CURRENT_USER();

-- Role
CREATE ROLE IF NOT EXISTS FINLAB_ROLE;
GRANT ROLE FINLAB_ROLE TO USER TCSIMM;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS FINLAB_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;
GRANT USAGE ON WAREHOUSE FINLAB_WH TO ROLE FINLAB_ROLE;

-- Database & schemas
CREATE DATABASE IF NOT EXISTS FINLAB;
CREATE SCHEMA IF NOT EXISTS FINLAB.BRONZE;
CREATE SCHEMA IF NOT EXISTS FINLAB.SILVER;
CREATE SCHEMA IF NOT EXISTS FINLAB.GOLD;

-- Give ownership to project role 
GRANT OWNERSHIP ON DATABASE FINLAB TO ROLE FINLAB_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA FINLAB.BRONZE TO ROLE FINLAB_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA FINLAB.SILVER TO ROLE FINLAB_ROLE COPY CURRENT GRANTS;
GRANT OWNERSHIP ON SCHEMA FINLAB.GOLD   TO ROLE FINLAB_ROLE COPY CURRENT GRANTS;

-- Set  defaults
ALTER USER TCSIMM
  SET DEFAULT_ROLE = FINLAB_ROLE,
      DEFAULT_WAREHOUSE = FINLAB_WH,
      DEFAULT_NAMESPACE = FINLAB.BRONZE;

-- 5) Switch and verify
USE ROLE FINLAB_ROLE;
USE WAREHOUSE FINLAB_WH;
USE DATABASE FINLAB;
USE SCHEMA BRONZE;

CREATE OR REPLACE TABLE PRICES_RAW (
  LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  TICKER STRING,
  DATA VARIANT
);

SHOW DATABASES;
SHOW SCHEMAS IN DATABASE FINLAB;
SHOW TABLES IN SCHEMA FINLAB.BRONZE;
