USE ROLE FINLAB_ROLE;
USE WAREHOUSE FINLAB_WH;
USE DATABASE FINLAB;

CREATE SCHEMA IF NOT EXISTS SILVER;

CREATE TABLE IF NOT EXISTS SILVER.PRICES (
  TICKER     STRING      NOT NULL,
  DT         DATE        NOT NULL,
  OPEN       FLOAT,
  HIGH       FLOAT,
  LOW        FLOAT,
  CLOSE      FLOAT,
  ADJ_CLOSE  FLOAT,
  VOLUME     NUMBER,
  LOAD_TS    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PRICES_PK UNIQUE (TICKER, DT)
);