USE ROLE FINLAB_ROLE;
USE WAREHOUSE FINLAB_WH;
USE DATABASE FINLAB;

MERGE INTO SILVER.PRICES AS T
USING (
  SELECT *
  FROM (
    SELECT
      TICKER, DT, OPEN, HIGH, LOW, CLOSE, ADJ_CLOSE, VOLUME, LOAD_TS,
      ROW_NUMBER() OVER (PARTITION BY TICKER, DT ORDER BY LOAD_TS DESC) AS rn
    FROM BRONZE.V_PRICES_RAW
    WHERE DT IS NOT NULL
      AND CLOSE IS NOT NULL
  )
  WHERE rn = 1
) AS S
ON  T.TICKER = S.TICKER
AND T.DT     = S.DT
WHEN MATCHED THEN UPDATE SET
  OPEN      = S.OPEN,
  HIGH      = S.HIGH,
  LOW       = S.LOW,
  CLOSE     = S.CLOSE,
  ADJ_CLOSE = S.ADJ_CLOSE,
  VOLUME    = S.VOLUME,
  LOAD_TS   = S.LOAD_TS
WHEN NOT MATCHED THEN INSERT (TICKER, DT, OPEN, HIGH, LOW, CLOSE, ADJ_CLOSE, VOLUME, LOAD_TS)
VALUES (S.TICKER, S.DT, S.OPEN, S.HIGH, S.LOW, S.CLOSE, S.ADJ_CLOSE, S.VOLUME, S.LOAD_TS);
